src/core/ls.js

Previously we had to do the extra sort due to ipfs/go-ipfs#5181
Now that's been resolved & released we can remove it, yay!
License: MIT
Signed-off-by: achingbrain <alex@achingbrain.net>

fix: removes extra sort added to ensure go compatibility

---

package.json

Upgrade dependencies in the context of [js-ipfs/pull/1617](https://github.com/ipfs/js-ipfs/pull/1617)
This has a circular dependency with `js-ipfs` and needs its version updated with `interface-datastore@0.6.0`

[WIP] chore: upgrade dependencies

---

src/cli/read.js
src/core/stat.js
src/core/utils/add-link.js
src/core/utils/constants.js

* Restrict how deeply directory trees are listed
* Use onEnd with file reads instead of collect to not buffer the file in memory
* Convert pre-existing files to hamt-sharded directories
* Replace files in hamt-sharded directories based on previous prefix
License: MIT
Signed-off-by: achingbrain <alex@achingbrain.net>

perf: do not list directory contents when statting files

---

src/core/utils/add-link.js
src/core/utils/hamt-utils.js
src/core/utils/remove-link.js
test/helpers/create-shard.js
test/helpers/create-sharded-directory.js
test/helpers/create-two-shards.js
test/helpers/find-tree-with-depth.js
test/helpers/index.js
test/helpers/print-tree.js
test/rm.spec.js
test/stat.spec.js
test/write.spec.js

Ensures hashes of sharded directories are the same after adding/removing nodes as if they'd been imported by the importer in their final state.
License: MIT
Signed-off-by: achingbrain <alex@achingbrain.net>

fix: make sure hashes are the same after shard changes

---

package.json
test/helpers/index.js

The `inMemory` util is going away to remove dependence on IPFS. This PR switches to using the `ipld-in-memory` module which does the same thing.

refactor: use ipld-in-memory module

---

package.json
src/http/cp.js
src/http/flush.js
src/http/index.js
src/http/ls.js
src/http/mkdir.js
src/http/mv.js
src/http/read.js
src/http/rm.js
src/http/stat.js
src/http/write.js

This PR refactors the HTTP API for use with Hapi 18 in preparation for https://github.com/ipfs/js-ipfs/pull/1844.
The current code works with Hapi 16. This is now two major versions behind the current version and we need to update our code to keep up to date with the latest bug and security fixes and performance improvements.
Hapi 17 introduced significant breaking changes, along with a switch from a callback API to a promises API hence the code changes to support this are also significant.
Note the following additional changes:
1. There's no need to explicitly reply with an error response - just throw the error and the [error handler](https://github.com/ipfs/js-ipfs/pull/1844/files#diff-bb0841ac950b1a35d4ae94352c87efd0) will construct the appropriate response - so the instances where …

refactor: migrate to hapi 18

---

src/cli/cp.js
src/cli/flush.js
src/cli/ls.js
src/cli/mkdir.js
src/cli/mv.js
src/cli/read.js
src/cli/rm.js
src/cli/stat.js
src/cli/write.js

Using getIpfs gives the handlers the power to create an IPFS when needed instead of having to create it upfront for all handlers even if they don't use it. It allows operations like `echo "hello" | jsipfs add -q | jsipfs cid base32` to work without `jsipfs cid base32` failing because it's trying to acquire a repo lock when it doesn't use IPFS at all.

[WIP] refactor: use getIpfs not ipfs from argv

---

src/core/utils/create-lock.js
src/core/utils/hamt-utils.js
src/core/utils/remove-link.js

Previously we nulled out the reference to the callback and caught any error that was thrown - this isn't necessary as using the two-arg version of `Promise.then` means only one handler will be invoked, not both.

chore: pass callback as onFulfilled and onRejected

---

src/http/read.js

When using the legacy `count` param, it's value wasn't being validated or coerced into an integer from a string.
It meant that a call to `http://localhost:5001/api/v0/files/read?offset=0&count=4096&arg=/gif/515f726a7087d.jpg&stream-channels=true` would produce a `count` value of `"4096"` and cause MFS to read the whole file!
There should probably be some better validation at the exporter level too.

fix: validate and coerce count param for read in HTTP API

---

package.json
src/core/ls-pull-stream.js
src/core/mkdir.js
src/core/stat.js
src/core/utils/to-trail.js

Allows MFS to use the unixfs exporter that exports CID instances without API changes.
refs https://github.com/ipfs/interface-js-ipfs-core/issues/394
Depends on:

refactor: use unixfs exporter with CID instances

---

src/core/utils/add-link.js
test/helpers/create-shard.js
test/write.spec.js

If you have a shard like:
```
F1
A0
C8myfile
```
And you add a file that causes `C8myfile` to become a subshard, previously you would end up with this:
```
F1
A0
C8
C8
B3myfile
82newfile
```
This PR ensures you get the correct structure:
```
F1
A0
C8
B3myfile
82newfile
```
When we update a shard, we re-create a portion of the shard in order to update the existing structure, this avoids loading the entire shard which could be expensive.  Previously we weren't descending into the newly created sub-shard to add the correct portion to the existing shard.
Fixes #45

fix: correct hamt structure when modifying deep sub-shards

---

src/core/utils/add-link.js
src/core/utils/hamt-utils.js
test/write.spec.js

I'd assumed that adding a file to a HAMT shard involved either adding a link, updating a link or replacing a link with a subshard that contains the files.
You can have files that result in a subshard being created that contains a subshard with the files in.
This PR handles that outcome.

fix: handle shard updates that create subshards of subshards

---

src/core/ls-pull-stream.js
src/core/stat.js
test/ls.spec.js
test/stat.spec.js

Right now we can only `ls` and `stat` `dag-pb` nodes - this PR allows us to handle `raw` nodes when `stat`ing and `ls`ing IPFS paths.

feat: handle raw nodes in mfs

---

package.json
src/core/stat.js
test/stat.spec.js

Doesn't do much as I'm not really sure what we should return for the fields, but at least it doesn't error out now.

fix: return the CID for dag-cbor nodes

---

package.json
src/http/cp.js
src/http/flush.js
src/http/ls.js
src/http/mkdir.js
src/http/mv.js
src/http/read.js
src/http/rm.js
src/http/stat.js
src/http/write.js

They moved to `@hapi` namespace and now spew warnings on npm install.
resolves #54
refs https://github.com/ipfs/js-ipfs/issues/2225

chore: update hapi deps

---

package.json
src/http/write.js

Remove old event emitter based multipart parser in favour of shiny new async iterator version.

chore: upgrade ipfs-multipart

---

package.json
src/core/utils/create-lock.js

Will need backporting to the 0.12.x branch to get `ipfs/js-ipfs#2379` into `v0.38.0`

chore: upgrade mortice to latest version

---

src/http/ls.js

The new `ipfs-http-client` sets the `stream` option by default. When enabled, the MFS HTTP API [fails this test](https://github.com/ipfs/interface-js-ipfs-core/blob/c766dbff654fd259f7094070ee71858091898750/src/files-mfs/ls.js#L106-L112) because it waits for the first item before sending a response. Since no items are yielded and the stream ends it waits forever.

fix: response for empty dir when ?stream=true

---

src/cli/stat.js
test/cli/stat.js

Previous:
```console
Mode: 420
Mtime: undefined
```
New:
```console
Mode: drwxr-xr-x
Mtime: -
```

fix: fix formatting of mode and optional mtimes

---

src/core/write.js
test/core/write.js

There was a test for this but it didn't check the contents of the entire file, only starting from the difference between the offset and the file length.  Oops.
Fixes #53

fix: allow writing starting at offset beyond file length
